name: Build

on:
  workflow_dispatch:
   push:
    

jobs:
  build:
    name: Build
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore Packages
      run: nuget restore SonicServer.sln

    - name: Build Solution
      run: msbuild.exe SonicServer.sln
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.6
      with:
    # Artifact name
        name: build
    # A file, directory or wildcard pattern that describes what to upload
        path: SonicServer\bin\Debug\net8.0-windows\
      
